DINO_PATCH_SIZE = 16

TASK_TYPE_DYNAMIC_PATCH = "dynamic_patch"
TASK_TYPE_REFINEMENT_PATCH = "refinement_patch"
TASK_TYPE_THUMBNAIL = "thumbnail"
SUPPORTED_TASK_TYPES = frozenset({
    TASK_TYPE_DYNAMIC_PATCH,
    TASK_TYPE_REFINEMENT_PATCH,
    TASK_TYPE_THUMBNAIL,
})
