DINO_PATCH_SIZE = 16

TASK_TYPE_DYNAMIC_PATCH = "dynamic_patch"
TASK_TYPE_THUMBNAIL = "thumbnail"
SUPPORTED_TASK_TYPES = frozenset({
    TASK_TYPE_DYNAMIC_PATCH,
    TASK_TYPE_THUMBNAIL,
})

ANOMALY_DISTANCE_NORMALIZED_L2 = "normalized_l2"
ANOMALY_DISTANCE_COSINE = "cosine"
SUPPORTED_ANOMALY_DISTANCES = frozenset({
    ANOMALY_DISTANCE_NORMALIZED_L2,
    ANOMALY_DISTANCE_COSINE,
})
